import { ThemeProvider } from "@/components/theme-provider";
import { Button } from "@/components/ui/button";
import LoggoutButton from "@/src/auth/LoggoutButton";
import { getAuthSession } from "@/src/lib/auth";
import { SessionType } from "@/src/types/types";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import Link from "next/link";
import FormPost from "../components/FormPost";
import { ModeToggle } from "../components/ToggleTheme";
import "../globals.css";
const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const session = (await getAuthSession()) as SessionType;

  return (
    <html lang="en">
      <body className={inter.className}>
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
        >
          <ModeToggle />
          <LoggoutButton />
          <Button asChild>
            <Link rel="stylesheet" href={"/"}>
              Home
            </Link>
          </Button>
          <FormPost session={session} />

          {session && (
            <Button asChild>
              <Link rel="stylesheet" href={"/user/" + session.user.id}>
                Profile
              </Link>
            </Button>
          )}

          {children}
        </ThemeProvider>
      </body>
    </html>
  );
}
